<?php
$l['number'] 						= 'Reference';
$l['date'] 							= 'Billing date';
$l['due'] 							= 'Due date';
$l['to'] 							= 'Billing to';
$l['ship']							= 'Details';
$l['from'] 							= 'Our information';
$l['product'] 						= 'Services';
$l['area'] 						    = 'Area';
$l['rate'] 						    = 'R/SqFt';
$l['discount'] 						= 'Discount';
$l['subTotal'] 						= 'Total';
$l['total'] 						= 'Total';
$l['page'] 							= 'Page';
$l['page_of'] 						= 'of';
?>